# SPDX-License-Identifier: MIT
import logging
import click
import sqlalchemy as s
from sqlalchemy import select, func

from collectoss.application.cli import (
    test_connection,
    test_db_connection,
    with_database,
    DatabaseContext,
)
from collectoss.application.db.models.augur_data import Commit

# from collectoss.application.db.session import DatabaseSession
from datetime import datetime
from collectoss.application.db.models import Repo

from ._cli_util import get_db_version

from alembic.config import Config
from alembic import command

logger = logging.getLogger(__name__)


@click.group("selftest", short_help="CollectOSS self-testing utilities")
@click.pass_context
def cli(ctx):
    ctx.obj = DatabaseContext()


def check_database_parity_with_versioned_model() -> list:
    """Checks for alignent between the versioned SQLAlchemy models and the actual database state

    Returns:
        list: a list of diff entries in alembic's format
    """
    alembic_cfg = Config("alembic.ini")
    try:
        # 2. Call the 'check' command
        # This will raise an AutogenerateDiffsDetected error if 
        # the database is out of sync with the models.
        command.check(alembic_cfg)
        return []
        
        
    except AutogenerateDiffsDetected as e:
        return list(e.diffs)


@cli.command("report")
@test_connection
@test_db_connection
@with_database
@click.pass_context
def run_selftest_report(ctx):
    """
    Run queries to evaluate various aspects of the collectoss system's functioning and produce a report
    """
    click.echo('Generating CollectOSS selftest report....')

    model_diffs = check_database_parity_with_versioned_model()
    
    cmt_author_name_issue_233_query = (
        select(func.count())
        .select_from(Commit)
        .where(Commit.cmt_author_name == '')
    )
    cmt_author_name_issue_233_count = None

    with ctx.obj.engine.begin() as connection:
        cmt_author_name_issue_233_count = connection.execute(cmt_author_name_issue_233_query).scalar_one()
        click.echo(f'Issue 233 count: {cmt_author_name_issue_233_count} commit files in the `commits` table contain authors with an empty string as their name')
