# SPDX-License-Identifier: MIT
import logging
from typing import Union
import click
import sqlalchemy as s
from sqlalchemy import Constraint, ForeignKeyConstraint, Index, select, func, Table

from collectoss.application.cli import (
    test_connection,
    test_db_connection,
    with_database,
    DatabaseContext,
)
from collectoss.application.db.models.augur_data import Commit

# from collectoss.application.db.session import DatabaseSession
from datetime import datetime
from collectoss.application.db.models import Repo

from ._cli_util import get_db_version

from alembic.config import Config, MessagingOptions, Namespace
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected


logger = logging.getLogger(__name__)


@click.group("selftest", short_help="CollectOSS self-testing utilities")
@click.pass_context
def cli(ctx):
    ctx.obj = DatabaseContext()


def check_database_parity_with_versioned_model() -> list:
    """Checks for alignent between the versioned SQLAlchemy models and the actual database state

    Returns:
        list: a list of diff entries in alembic's format
    """
    alembic_cfg = Config("alembic.ini")
    try:
        # 2. Call the 'check' command
        # This will raise an AutogenerateDiffsDetected error if 
        # the database is out of sync with the models.
        command.check(alembic_cfg)
        return []
        
        
    except AutogenerateDiffsDetected as e:
        return list(e.diffs)


def output_alembic_diff(diff: list[Union[tuple, list]]):
    """Print an alembic diff for consumption

    Args:
        diff (list): A diff list created by Alembic
    """
    if len(diff) == 0:
        print("✅ No drift detected. Database is in sync with models.")
        return

    print(f"❌ Database drift detected:")


    for change in diff:
        if isinstance(change, tuple):
            action, category = change[0].split("_")

            action_text = ""

            if action == "add":
                action_text = "found in models but not database"
            elif action == "modify":
                action_text = "modified"
            elif action == "remove":
                action_text = "found in database but not models"
            

            if category == "table":
                table_def:Table = change[1]
                print(f"Table {table_def.name} in schema {table_def.schema}")
                
            elif category == "column":
                _, _, table_name, col_def = change
                print(f"Column {col_def.name} in table {table_name}")

            elif category == "fk":
                fk_constraint_def:ForeignKeyConstraint = change[1]
                fk_name = f" called '{fk_constraint_def.name}'" if fk_constraint_def.name else ""
                print(f"Foreign Key{fk_name} on `{fk_constraint_def.table.columns[0]}` linking to `{fk_constraint_def.table}`")

                # TODO: attributes
            elif category == "index":
                index_def:Index = change[1]
                print(f"Index {index_def.name}")
            elif category == "constraint":
                constraint_def:Constraint = change[1]
                constraint_name = f" called '{constraint_def.name}'" if constraint_def.name else ""
                constraint_type = constraint_def.__class__.__name__ or "Constraint"
                constraint_covers = [c.name for c in constraint_def.columns]
                print(f"{constraint_type}{constraint_name} covering {','.join(constraint_covers)}")

            else:
                print("unknown type found in alembic diff")
                print(change)

            print(f"\t{action_text}")



        elif isinstance(change, list):
            pass
            # TODO: probably a modify_nullable, handle this



@cli.command("report")
@test_connection
@test_db_connection
@with_database
@click.pass_context
def run_selftest_report(ctx):
    """
    Run queries to evaluate various aspects of the collectoss system's functioning and produce a report
    """
    click.echo('Generating CollectOSS selftest report....')

    model_diffs = check_database_parity_with_versioned_model()
    
    cmt_author_name_issue_233_query = (
        select(func.count())
        .select_from(Commit)
        .where(Commit.cmt_author_name == '')
    )
    cmt_author_name_issue_233_count = None

    with ctx.obj.engine.begin() as connection:
        cmt_author_name_issue_233_count = connection.execute(cmt_author_name_issue_233_query).scalar_one()
        click.echo(f'Issue 233 count: {cmt_author_name_issue_233_count} commit changes in the `commits` table contain authors with an empty string as their name')

    print(output_alembic_diff(model_diffs))