"""associate instance and keys

Revision ID: 44
Revises: 43
Create Date: 2026-06-28 18:07:31.814350

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '44'
down_revision = '43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_oauth', sa.Column('instance', sa.Integer(), nullable=True), schema='operations')
    op.create_foreign_key('apikey_instance_fkey', 'worker_oauth', 'forge_instance', ['instance'], ['id'], source_schema='operations', referent_schema='operations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('apikey_instance_fkey', 'worker_oauth', schema='operations', type_='foreignkey')
    op.drop_column('worker_oauth', 'instance', schema='operations')
    # ### end Alembic commands ###
