"""remove redundant pr constraint

Revision ID: 44
Revises: 43
Create Date: 2026-06-27 15:41:43.276187

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '44'
down_revision = '43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique-prx'), 'pull_requests', schema='data', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique-prx'), 'pull_requests', ['repo_id', 'pr_src_id'], schema='data')
    # ### end Alembic commands ###
