"""add facade path column

Revision ID: 45
Revises: 44
Create Date: 2026-09-28 11:44:57.974030

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '45'
down_revision = '44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_status', sa.Column('facade_clone_path', sa.String(), nullable=True), schema='operations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_status', 'facade_clone_path', schema='operations')
    # ### end Alembic commands ###
