"""rename DB columns from old name

Revision ID: 45
Revises: 44
Create Date: 2026-07-16 10:49:58.385233

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_materialized_view import PGMaterializedView
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql
    
# revision identifiers, used by Alembic.
revision = '45'
down_revision = '44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind() 
    conn.execute(sql_text("ALTER TABLE operations.augur_settings RENAME TO operations.legacy_settings;"))
    conn.execute(sql_text("ALTER TABLE spdx.augur_repo_map RENAME TO spdx.repo_map;"))
    
    conn.execute(sql_text("ALTER SEQUENCE spdx.augur_repo_map_map_id_seq RENAME TO spdx.repo_map_map_id_seq;"))

    conn.execute(sql_text('ALTER TABLE data.pull_requests RENAME CONSTRAINT "pull_requests_pr_augur_contributor_id_fkey" TO "pull_requests_contributor_id_fkey"'))

    conn.execute(sql_text("ALTER TABLE data.pull_requests RENAME COLUMN pr_augur_contributor_id TO pr_contributor_id;"))
    conn.execute(sql_text("ALTER TABLE data.pull_requests RENAME COLUMN pr_augur_issue_id TO pr_issue_id;"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind() 
    conn.execute(sql_text("ALTER TABLE data.pull_requests RENAME COLUMN pr_issue_id TO pr_augur_issue_id;"))
    conn.execute(sql_text("ALTER TABLE data.pull_requests RENAME COLUMN pr_contributor_id TO pr_augur_contributor_id;"))
    
    conn.execute(sql_text('ALTER TABLE data.pull_requests RENAME CONSTRAINT "pull_requests_contributor_id_fkey" TO "pull_requests_pr_augur_contributor_id_fkey"'))

    conn.execute(sql_text("ALTER SEQUENCE spdx.repo_map_map_id_seq RENAME TO spdx.augur_repo_map_map_id_seq;"))

    conn.execute(sql_text("ALTER TABLE spdx.repo_map RENAME TO spdx.augur_repo_map;"))
    conn.execute(sql_text("ALTER TABLE operations.legacy_settings RENAME TO operations.augur_settings;"))
    
    
    # ### end Alembic commands ###
