"""rename

Revision ID: 39
Revises: 38
Create Date: 2026-04-18 19:57:02.493560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39'
down_revision = '38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contributors', 'cntrb_email',
               existing_type=sa.VARCHAR(),
               comment='This needs to be here for matching contributor ids to the commit information. ',
               existing_comment='This needs to be here for matching contributor ids, which are augur, to the commit information. ',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('contributors', 'cntrb_type',
               existing_type=sa.VARCHAR(),
               comment='Present in another models. It is not currently used. ',
               existing_comment='Present in another models. It is not currently used in Augur. ',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('pull_requests', 'pr_augur_issue_id',
               existing_type=sa.BIGINT(),
               comment='This is to link to the internal ID for the related issue',
               existing_comment='This is to link to the augur stored related issue',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('pull_requests', 'pr_augur_contributor_id',
               existing_type=sa.UUID(),
               comment='This is to link to the contributor record. ',
               existing_comment='This is to link to the augur contributor record. ',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('repo_insights_records', 'tool_source',
               existing_type=sa.VARCHAR(),
               comment='Standard Collection Metadata',
               existing_comment='Standard Augur Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('repo_insights_records', 'tool_version',
               existing_type=sa.VARCHAR(),
               comment='Standard Collection Metadata',
               existing_comment='Standard Augur Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('repo_insights_records', 'data_source',
               existing_type=sa.VARCHAR(),
               comment='Standard Collection Metadata',
               existing_comment='Standard Augur Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('repo_insights_records', 'data_collection_date',
               existing_type=postgresql.TIMESTAMP(precision=6),
               comment='Standard Collection Metadata',
               existing_comment='Standard Augur Metadata',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'tool_source',
               existing_type=sa.VARCHAR(),
               comment='Standard Collection Metadata',
               existing_comment='Standard Augur Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'tool_version',
               existing_type=sa.VARCHAR(),
               comment='Standard Collection Metadata',
               existing_comment='Standard Augur Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'data_source',
               existing_type=sa.VARCHAR(),
               comment='Standard Collection Metadata',
               existing_comment='Standard Augur Metadata',
               existing_nullable=True,
               schema='augur_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic_model_meta', 'data_source',
               existing_type=sa.VARCHAR(),
               comment='Standard Augur Metadata',
               existing_comment='Standard Collection Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'tool_version',
               existing_type=sa.VARCHAR(),
               comment='Standard Augur Metadata',
               existing_comment='Standard Collection Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'tool_source',
               existing_type=sa.VARCHAR(),
               comment='Standard Augur Metadata',
               existing_comment='Standard Collection Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('repo_insights_records', 'data_collection_date',
               existing_type=postgresql.TIMESTAMP(precision=6),
               comment='Standard Augur Metadata',
               existing_comment='Standard Collection Metadata',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='augur_data')
    op.alter_column('repo_insights_records', 'data_source',
               existing_type=sa.VARCHAR(),
               comment='Standard Augur Metadata',
               existing_comment='Standard Collection Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('repo_insights_records', 'tool_version',
               existing_type=sa.VARCHAR(),
               comment='Standard Augur Metadata',
               existing_comment='Standard Collection Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('repo_insights_records', 'tool_source',
               existing_type=sa.VARCHAR(),
               comment='Standard Augur Metadata',
               existing_comment='Standard Collection Metadata',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('pull_requests', 'pr_augur_contributor_id',
               existing_type=sa.UUID(),
               comment='This is to link to the augur contributor record. ',
               existing_comment='This is to link to the contributor record. ',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('pull_requests', 'pr_augur_issue_id',
               existing_type=sa.BIGINT(),
               comment='This is to link to the augur stored related issue',
               existing_comment='This is to link to the internal ID for the related issue',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('contributors', 'cntrb_type',
               existing_type=sa.VARCHAR(),
               comment='Present in another models. It is not currently used in Augur. ',
               existing_comment='Present in another models. It is not currently used. ',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('contributors', 'cntrb_email',
               existing_type=sa.VARCHAR(),
               comment='This needs to be here for matching contributor ids, which are augur, to the commit information. ',
               existing_comment='This needs to be here for matching contributor ids to the commit information. ',
               existing_nullable=True,
               schema='augur_data')
    # ### end Alembic commands ###
